# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v3

      - name: Running Python scripts
        run: |
          export PYTHONUNBUFFERED=1
          pip install -r requirements.txt
          python twitter/fetch.py
          python twitter/parse.py
          cp twitter/tweets/compiled.json website/_data/

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Running rubygems scripts
        working-directory: website
        run: |
          bundle init
          bundle add jekyll --skip-install --version "~> 3.9"
          bundle add kramdown-parser-gfm --skip-install --version "~> 1.1"
          bundle lock

      - uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true
          jekyll_src: website

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          force_orphan: true
